import React from 'react';

export default function InvisibleAICaseStudy() {
    return (
        <article className="pt-32 pb-20 px-6 md:px-12 max-w-5xl mx-auto">

            <header className="mb-16 text-center">
                <h1 className="text-4xl md:text-6xl font-black tracking-tighter text-ink mb-6">Invisible AI: Video Review Interface</h1>
                <p className="text-xl text-ink/70 font-medium max-w-3xl mx-auto text-balance">
                    Next-generation computer vision interfaces for industrial performance.
                </p>
            </header>

            {/* Hero Image / Header */}
            <div className="w-full h-[400px] md:h-[500px] rounded-3xl bg-slate border border-white/40 shadow-sm overflow-hidden mb-16 relative">
                <div className="absolute inset-0 bg-gradient-to-br from-blurple/10 to-transparent z-10" />
                {/* We will load the actual image when available, using placeholder for now */}
                <div className="absolute inset-0 flex items-center justify-center text-ink/40 font-mono text-sm">
                    [ header.png — loads on live site ]
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-12 mb-20">
                <div className="md:col-span-2 space-y-12">

                    <section className="prose prose-lg prose-slate max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">About the Project</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            Invisible AI builds computer vision software that tracks worker safety and operational progress across factory camera networks. As a UX Consultant, I was brought in to redesign the video review interface—the core application where site managers and engineers search for, watch, and act on AI-organized footage.
                        </p>
                    </section>

                    <section className="prose prose-lg prose-slate max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">The Design Challenge</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            The central challenge was managing the volume of data generated by the system’s AI. While the computer vision automatically groups footage from across 500+ cameras, returning everything without hierarchy creates massive cognitive overload. My goal was to build an interface that makes AI-organized video feel focused and actionable rather than overwhelming.
                        </p>
                    </section>

                    <section className="prose prose-lg prose-slate max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">Research & Insights</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            Research revealed that while site managers valued the AI's thoroughness, they needed a way to scope results; 99% of searches were for specific body numbers on individual lines. I also found that users were manually jumping between adjacent cameras because the results didn't help them understand spatial relationships. The AI's thoroughness had become a UX liability that needed filtering and context to solve.
                        </p>
                        <div className="w-full h-64 bg-slate rounded-xl border border-white/40 flex items-center justify-center font-mono text-sm text-ink/40 mb-6">[ research.png — loads on live site ]</div>
                    </section>

                    <section className="prose prose-lg prose-slate max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">Key Design Decisions</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            The redesign introduced line-level filtering as the primary organizational layer, immediately scoping results to specific production areas. I also updated the video player layout to surface spatial context—showing each clip’s relationship to adjacent cameras—and added clear affordances for users to verify and correct the AI's occasional misidentifications.
                        </p>
                        <div className="w-full h-96 bg-slate rounded-xl border border-white/40 flex items-center justify-center font-mono text-sm text-ink/40 mb-6">[ new_ui.png — loads on live site ]</div>
                    </section>

                    <section className="prose prose-lg prose-slate max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">System & Outcome</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            In parallel, I modernized the product's design system with industrial-grade components and documented guidelines. The outcome was a video review experience built for scale, addressing the tension of an AI that sees everything through an interface that helps users focus on what matters while providing a consistent foundation for future growth.
                        </p>
                    </section>

                </div>

                {/* Info Sidebar */}
                <aside className="md:col-span-1">
                    <div className="glass-card p-8 rounded-3xl">
                        <h3 className="text-lg font-bold text-ink mb-6 pb-4 border-b border-ink/10">Project Details</h3>

                        <div className="mb-8">
                            <h4 className="text-xs font-mono text-blurple uppercase tracking-wider mb-3">Responsibilities</h4>
                            <ul className="space-y-2 text-ink/80 font-medium list-disc list-inside">
                                <li>AI Interface Design</li>
                                <li>UX Research</li>
                                <li>Wireframing</li>
                                <li>Design System</li>
                            </ul>
                        </div>

                        <div className="mb-8">
                            <h4 className="text-xs font-mono text-blurple uppercase tracking-wider mb-3">Players</h4>
                            <ul className="space-y-2 text-ink/80 font-medium list-disc list-inside">
                                <li>UX Consultant</li>
                                <li>Site Managers</li>
                                <li>Engineers</li>
                                <li>Product Team</li>
                            </ul>
                        </div>

                        <div>
                            <h4 className="text-xs font-mono text-blurple uppercase tracking-wider mb-3">Tools</h4>
                            <ul className="space-y-2 text-ink/80 font-medium list-disc list-inside">
                                <li>Figma</li>
                                <li>FigJam</li>
                                <li>Material 3</li>
                            </ul>
                        </div>

                    </div>
                </aside>
            </div>
        </article>
    );
}
