import React from 'react';
import Hero3D from '../components/Hero3D';
import { CONTENT } from '../content';

export default function InvisibleAICaseStudy() {
    return (
        <article className="pt-0 pb-0 md:pt-32 md:pb-20 md:px-12 max-w-5xl mx-auto">

            <header className="mb-16 px-6 md:px-0 pt-16 md:pt-0 text-center">
                <h1 className="text-4xl md:text-6xl font-black tracking-tighter text-ink mb-6">Invisible AI Video Center</h1>
                <h1 className="text-4xl md:text-6xl font-black tracking-tighter text-appfg mb-6">Invisible AI Video Center</h1>
                <p className="text-xl text-appfg/70 font-medium max-w-3xl mx-auto text-balance">
                    Optimizing the video review interface for a computer vision platform.
                </p>
            </header>

            {/* Hero Image / Header */}
            <div className="w-full h-[400px] md:h-[500px] rounded-none md:rounded-3xl bg-appbg border-y md:border border-white/40 shadow-sm overflow-hidden mb-16 relative group transition-colors duration-300">
                <div className="absolute inset-0 bg-gradient-to-br from-blurple/10 to-transparent z-10 pointer-events-none" />
                <div className="absolute inset-0 bg-zinc-100 dark:bg-appbg flex items-center justify-center overflow-hidden transition-colors duration-300">
                    <Hero3D
                        modelUrl={`${import.meta.env.BASE_URL}${CONTENT.work.projects.find(p => p.slug === 'invisible-ai').modelUrl}`}
                        baseRotation={[0, -Math.PI / 2, 0]}
                        scale={0.015}
                        position={[0, -1.2, 0]}
                        mousePivotIntensity={[0.15, 0.02]} // Limit vertical tilt to prevent side monitors from clipping floor
                    />
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-12 mb-20 px-6 md:px-0 pb-20 md:pb-0">
                <div className="md:col-span-2 space-y-12">

                    <section className="prose prose-lg prose-slate dark:prose-invert max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">About the Project</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            Invisible AI builds computer vision software that tracks worker safety and operational progress across factory camera networks. As a UX Consultant, I was brought in to redesign the video review interface – the core application where site managers and engineers search for, watch, and act on AI-organized footage.
                        </p>
                    </section>

                    <section className="prose prose-lg prose-slate dark:prose-invert max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">The Design Challenge</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            The central challenge was making sense of the volume of data generated by the system’s AI. While the computer vision automatically grouped footage from across 500+ cameras, the existing interface had limited tools for navigating and filtering this footage. My goal was to design an intuitive interface that allowed users to take advantage of the volume of data without being overwhelmed.
                        </p>
                    </section>

                    <section className="prose prose-lg prose-slate dark:prose-invert max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">Research & Insights</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            Research revealed that while site managers valued the AI's thoroughness, they needed a way to scope results; <strong className="text-blurple">99% of searches were for specific body numbers on individual lines.</strong> I also found that users were manually jumping between adjacent cameras because the results didn't help them understand spatial relationships. Without filters and context, <strong className="text-blurple">the system was little more than a search engine for video clips.</strong>
                        </p>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            Using this research, I created a user flow to visualize the current experience and identify key areas for improvement.
                        </p>
                        <div className="w-full bg-slate rounded-2xl border border-white/40 overflow-hidden mb-6">
                            <img src={`${import.meta.env.BASE_URL}img/invisible_ai/research.png`} alt="UX Research visualization of complex factory camera networks" className="w-full h-auto object-cover" />
                        </div>
                    </section>

                    <section className="prose prose-lg prose-slate dark:prose-invert max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">Key Design Decisions</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            After several iterations, I landed on a design that introduced line-level filtering as the primary organizational layer, immediately scoping results to specific production areas. To future proof the design, I also included placeholder filters for additional data types that the company planned to integrate in the future.
                        </p>
                        <div className="w-full bg-slate rounded-2xl border border-white/40 overflow-hidden mb-6">
                            <img src={`${import.meta.env.BASE_URL}img/invisible_ai/wireframes.jpg`} alt="Video Center UI with two videos side-by-side and search results below with multiple filters" className="w-full h-auto object-cover" />
                            <div className="p-4 bg-white/50 dark:bg-white/5 backdrop-blur-md border-t border-white/20 dark:border-white/10">
                                <p className="text-xs font-mono text-ink/60 uppercase">Low-fidelity sketches</p>
                            </div>
                        </div>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            I updated the video player layout to take advantage of the AI groupings by allowing users to easily jump between adjacent cameras. The new layout also offered the ability to compare clips from multiple cameras side-by-side, helping them see how events unfold across the production line. For power users, the inclusion of CTAs for add-on apps like Smart Search and Digital Poka Yoke allowed them to quickly dig deeper into the footage and more comprehensively trace clip and camera relationships.
                        </p>
                        <div className="w-full bg-slate rounded-2xl border border-white/40 overflow-hidden mb-6">
                            <img src={`${import.meta.env.BASE_URL}img/invisible_ai/new_ui.png`} alt="Video Center UI with two videos side-by-side and search results below with multiple filters" className="w-full h-auto object-cover" />
                            <div className="p-4 bg-white/50 dark:bg-white/5 backdrop-blur-md border-t border-white/20 dark:border-white/10">
                                <p className="text-xs font-mono text-ink/60 uppercase">Final design</p>
                            </div>
                        </div>
                    </section>

                    <section className="prose prose-lg prose-slate dark:prose-invert max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">System & Outcome</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            In parallel, I modernized the product's design system with components that reflected Invisible AI's brand identity and documented guidelines. The outcome was a <strong className="text-blurple">video review experience built for scale,</strong> addressing the complexity of an AI that sees everything through an interface that helps users focus on what matters.
                        </p>
                        <div className="w-full bg-slate rounded-2xl border border-white/40 overflow-hidden mb-6">
                            <img src={`${import.meta.env.BASE_URL}img/invisible_ai/design-system.png`} alt="Design system components for Invisible AI" className="w-full h-auto object-cover" />
                            <div className="p-4 bg-white/50 dark:bg-white/5 backdrop-blur-md border-t border-white/20 dark:border-white/10">
                                <p className="text-xs font-mono text-ink/60 uppercase">Material Design card component updated with Invisible AI's typography, colors, and spacing</p>
                            </div>
                        </div>
                    </section>

                </div>

                {/* Info Sidebar */}
                <aside className="md:col-span-1">
                    <div className="glass-card p-8 rounded-3xl sticky top-32">
                        <h3 className="text-lg font-bold text-appfg mb-6 pb-4 border-b border-appfg/10 dark:border-white/10">Project Details</h3>

                        <div className="mb-8">
                            <h4 className="text-xs font-mono text-blurple uppercase tracking-wider mb-3">Responsibilities</h4>
                            <ul className="space-y-2 text-ink/80 font-medium list-disc list-inside">
                                <li>AI Interface Design</li>
                                <li>UX Research</li>
                                <li>Wireframing</li>
                                <li>Design System</li>
                            </ul>
                        </div>

                        <div className="mb-8">
                            <h4 className="text-xs font-mono text-blurple uppercase tracking-wider mb-3">Players</h4>
                            <ul className="space-y-2 text-ink/80 font-medium list-disc list-inside">
                                <li>UX Consultant</li>
                                <li>Site Managers</li>
                                <li>Engineers</li>
                                <li>Product Team</li>
                            </ul>
                        </div>

                        <div>
                            <h4 className="text-xs font-mono text-blurple uppercase tracking-wider mb-3">Tools</h4>
                            <ul className="space-y-2 text-ink/80 font-medium list-disc list-inside">
                                <li>Figma</li>
                                <li>FigJam</li>
                                <li>Material 3</li>
                            </ul>
                        </div>

                    </div>
                </aside>
            </div>
        </article>
    );
}
