import React from 'react';
import Hero3D from '../components/Hero3D';
import { CONTENT } from '../content';

export default function InvisibleAICaseStudy() {
    return (
        <article className="pt-0 pb-0 md:pt-32 md:pb-20 md:px-12 max-w-5xl mx-auto">

            <header className="mb-16 px-6 md:px-0 pt-16 md:pt-0 text-center">
                <h1 className="text-4xl md:text-6xl font-black tracking-tighter text-ink mb-6">Invisible AI: Video Review Interface</h1>
                <p className="text-xl text-ink/70 font-medium max-w-3xl mx-auto text-balance">
                    Next-generation computer vision interfaces for industrial performance.
                </p>
            </header>

            {/* Hero Image / Header */}
            <div className="w-full h-[400px] md:h-[500px] rounded-none md:rounded-3xl bg-slate border-y md:border border-white/40 shadow-sm overflow-hidden mb-16 relative group">
                <div className="absolute inset-0 bg-gradient-to-br from-blurple/10 to-transparent z-10 pointer-events-none" />
                <div className="absolute inset-0 bg-zinc-100 flex items-center justify-center overflow-hidden">
                    <Hero3D
                        modelUrl={`${import.meta.env.BASE_URL}${CONTENT.work.projects.find(p => p.slug === 'invisible-ai').modelUrl}`}
                        baseRotation={[0, -Math.PI / 2, 0]}
                        scale={0.015}
                        position={[0, -1.2, 0]}
                        mousePivotIntensity={[0.15, 0.02]} // Limit vertical tilt to prevent side monitors from clipping floor
                    />
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-12 mb-20 px-6 md:px-0 pb-20 md:pb-0">
                <div className="md:col-span-2 space-y-12">

                    <section className="prose prose-lg prose-slate max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">About the Project</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            Invisible AI builds computer vision software that tracks worker safety and operational progress across factory camera networks. As a UX Consultant, I was brought in to redesign the video review interface – the core application where site managers and engineers search for, watch, and act on AI-organized footage.
                        </p>
                    </section>

                    <section className="prose prose-lg prose-slate max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">The Design Challenge</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            The central challenge was managing the volume of data generated by the system’s AI. While the computer vision automatically groups footage from across 500+ cameras, returning everything without hierarchy creates massive cognitive overload. My goal was to build an interface that makes AI-organized video feel focused and actionable rather than overwhelming.
                        </p>
                    </section>

                    <section className="prose prose-lg prose-slate max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">Research & Insights</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            Research revealed that while site managers valued the AI's thoroughness, they needed a way to scope results; 99% of searches were for specific body numbers on individual lines. I also found that users were manually jumping between adjacent cameras because the results didn't help them understand spatial relationships. The AI's thoroughness had become a UX liability that needed filtering and context to solve.
                        </p>
                        <div className="w-full bg-slate rounded-2xl border border-white/40 overflow-hidden mb-6">
                            <img src={`${import.meta.env.BASE_URL}img/invisible_ai/research.png`} alt="UX Research visualization of complex factory camera networks" className="w-full h-auto object-cover" />
                        </div>
                    </section>

                    <section className="prose prose-lg prose-slate max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">Key Design Decisions</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            The redesign introduced line-level filtering as the primary organizational layer, immediately scoping results to specific production areas. I also updated the video player layout to surface spatial context – showing each clip’s relationship to adjacent cameras – and added clear affordances for users to verify and correct the AI's occasional misidentifications.
                        </p>
                        <div className="w-full bg-slate rounded-2xl border border-white/40 overflow-hidden mb-6">
                            <img src={`${import.meta.env.BASE_URL}img/invisible_ai/wireframes.jpg`} alt="Video Center UI with two videos side-by-side and search results below with multiple filters" className="w-full h-auto object-cover" />
                            <div className="p-4 bg-white/50 backdrop-blur-md border-t border-white/20">
                                <p className="text-xs font-mono text-ink/60 uppercase">Low-fidelity sketches</p>
                            </div>
                        </div>
                        <div className="w-full bg-slate rounded-2xl border border-white/40 overflow-hidden mb-6">
                            <img src={`${import.meta.env.BASE_URL}img/invisible_ai/new_ui.png`} alt="Video Center UI with two videos side-by-side and search results below with multiple filters" className="w-full h-auto object-cover" />
                            <div className="p-4 bg-white/50 backdrop-blur-md border-t border-white/20">
                                <p className="text-xs font-mono text-ink/60 uppercase">Final design</p>
                            </div>
                        </div>
                    </section>

                    <section className="prose prose-lg prose-slate max-w-none">
                        <h2 className="text-2xl font-bold tracking-tight text-ink mb-4">System & Outcome</h2>
                        <p className="text-ink/80 leading-relaxed mb-6">
                            In parallel, I modernized the product's design system with industrial-grade components and documented guidelines. The outcome was a video review experience built for scale, addressing the tension of an AI that sees everything through an interface that helps users focus on what matters while providing a consistent foundation for future growth.
                        </p>
                    </section>

                </div>

                {/* Info Sidebar */}
                <aside className="md:col-span-1">
                    <div className="glass-card p-8 rounded-3xl">
                        <h3 className="text-lg font-bold text-ink mb-6 pb-4 border-b border-ink/10">Project Details</h3>

                        <div className="mb-8">
                            <h4 className="text-xs font-mono text-blurple uppercase tracking-wider mb-3">Responsibilities</h4>
                            <ul className="space-y-2 text-ink/80 font-medium list-disc list-inside">
                                <li>AI Interface Design</li>
                                <li>UX Research</li>
                                <li>Wireframing</li>
                                <li>Design System</li>
                            </ul>
                        </div>

                        <div className="mb-8">
                            <h4 className="text-xs font-mono text-blurple uppercase tracking-wider mb-3">Players</h4>
                            <ul className="space-y-2 text-ink/80 font-medium list-disc list-inside">
                                <li>UX Consultant</li>
                                <li>Site Managers</li>
                                <li>Engineers</li>
                                <li>Product Team</li>
                            </ul>
                        </div>

                        <div>
                            <h4 className="text-xs font-mono text-blurple uppercase tracking-wider mb-3">Tools</h4>
                            <ul className="space-y-2 text-ink/80 font-medium list-disc list-inside">
                                <li>Figma</li>
                                <li>FigJam</li>
                                <li>Material 3</li>
                            </ul>
                        </div>

                    </div>
                </aside>
            </div>
        </article>
    );
}
